Developer
maya88en/The-Next-Web pull request #1
Opened 2019-07-30 11:42 UTC by Anna-Myzukina

2019-07-30 12:05 UTC, mosaaleb commented
Reviewing

2019-07-30 12:48 UTC, mosaaleb requested changes
### Hi @Anna-Myzukina, @maya88en :wave:

#### Good start working on responsive design. Amazing job turning your css file into mini-bootstrap :clap:.

There is some issues related to file paths:

- Since our css file is not in the same directory with the `index.html` file we need the inclusion of the stylesheets to have the corrent path with `<link rel="stylesheet" href="assets/style.css">` it was `href="style.css"`

I have fixed it on my local repo to start the review, but please make sure to fix it before requesting a new code review.

- **Also** we need to fix [image paths](https://www.w3schools.com/html/html_filepaths.asp) for all image tags and also css background-image property, as all these images are not showing. 

![Screenshot from 2019-07-30 14-26-17](https://user-images.githubusercontent.com/4246637/62129045-051c5880-b2d6-11e9-8418-bfd68c290ebf.png)

- The webpage is still not responsive as it maintains the same layout on all screen sizes

This image from mobile screen
![Screenshot from 2019-07-30 14-35-07](https://user-images.githubusercontent.com/4246637/62129541-3fd2c080-b2d7-11e9-8b1b-e808102b687d.png)

- Let's fill in the readme file properly with markdown syntax instead of html.


Please fix these issues and submit a new code review.
Happy coding :computer:

2019-07-30 12:48 UTC, mosaaleb commented on index.html
> +    <link rel="apple-touch-icon" sizes="72x72"
Could you please tell me what is the purpose of including all these links inside your `<head>` tag?

2019-07-30 12:54 UTC, Anna-Myzukina commented on index.html
> +    <link rel="apple-touch-icon" sizes="72x72"
It`s for the favicon in different sizes of the screen :)

2019-08-03 11:22 UTC, bolah2009 commented
Currently been reviewed

2019-08-03 12:39 UTC, bolah2009 requested changes
## Nice Job Team :clap: 

The clone looks nice, however, I would suggest making it more responsive since the main objective of the project is to make a responsive clone of [this page](https://thenextweb.com/). See below (check the full [page](https://thenextweb.com/) for more section that needs to be responsive:

| Current | Preferred |
| :-----: | :-----: |
| ![newsweek current](https://user-images.githubusercontent.com/36057474/62411981-6b192080-b5f3-11e9-814a-79489c209d0a.gif)  |  ![newsweek preferred ](https://user-images.githubusercontent.com/36057474/62406175-35e2e300-b59f-11e9-9380-cc9fcb04eae8.gif) |

You can recreate this issue (Image above) by using the console on chrome **(Inspect `Ctrl+Shift+I`)** and the **Toggle device toolbar** `Ctrl+Shift+M`. This way you can simulate how the app will render on small to widescreen devices. As a solution, I would suggest using media queries to change the position and structure of the app for different screens.

### Optional but strongly recommended

- Note [this comment](#discussion_r310349641) on file path. Currently, it is preventing the [clone](https://raw.githack.com/maya88en/The-Next-Web/developer/index.html) on raw.githack.com from rendering all asset files. 

- Check out [these errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2Fmaya88en%2FThe-Next-Web%2Fdeveloper%2Findex.html) too.

Good luck with your next submission.

Cheers
[Bola](https://bolabuari.com/)

2019-08-03 12:39 UTC, bolah2009 commented on index.html
> +    <link rel="stylesheet" href="../The-Next-Web/assets/style.css">
`SUGGESTION`

Since the `assets` directory and `index.html` is in the same folder consider using `href="assets/style.css"` instead. 

This works better when the root directory is renamed (or changed), for example [the clone](https://raw.githack.com/maya88en/The-Next-Web/developer/index.html) on `raw,githack.com` is reading this as `https://raw.githack.com/maya88en/The-Next-Web/The-Next-Web/assets/style.css` instead of `https://raw.githack.com/maya88en/The-Next-Web/developer/assets/style.css`. 

> To reference a file in a subdirectory, write the directory name in front of the path, plus a forward slash, e.g. subdirectory/my-image.jpg.

Learn more [here](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files#File_paths)

2019-08-03 12:39 UTC, bolah2009 commented on index.html
> +                    <img src="../The-Next-Web/assets/img/Netflix-mobile.jpg" alt="">
Please check [this comment]() on relative file paths.

2019-08-03 12:39 UTC, bolah2009 commented on index.html
> +                    <img src="../The-Next-Web/assets/img/sale_image.jpg" alt="wi-fi photo">
Please check [this comment]() on relative file paths.

2019-08-03 12:39 UTC, bolah2009 commented on index.html
> +                    <img src="../The-Next-Web/assets/img/sale_image.jpg" alt="wi-fi photo">
Please check [this comment]() on relative file paths.

2019-08-03 12:39 UTC, bolah2009 commented on index.html
> +                    <img src="../The-Next-Web/assets/img/apple-logo.jpg" alt="">
Please check [this comment]() on relative file paths.

2019-08-03 12:39 UTC, bolah2009 commented on index.html
> +                    <h1>
`SUGGESTION`

Consider using `h2-h6` element here instead. `<h1>` should be used only as a top-level heading. 

> Using only h1 elements in a HTML document results in a flat document outline as heading element semantics are conveyed to users as per the numeric in the heading element tag name.

Learn more [here](https://www.w3.org/wiki/HTML/Usage/Headings/h1only)

2019-08-03 12:39 UTC, bolah2009 commented on index.html
> +                    <h1>
`SUGGESTION`

Check [this comment](#) on using `h1` as top-level heading only.

2019-08-03 12:39 UTC, bolah2009 commented on index.html
> +                    <h1>
`SUGGESTION`

Check [this comment](#) on using `h1` as top-level heading only.

2019-08-03 12:39 UTC, bolah2009 commented on index.html
> +                    <h1>LATEST
`SUGGESTION`

Check [this comment](#) on using `h1` as top-level heading only.

2019-08-03 12:39 UTC, bolah2009 commented on index.html
> +                    <h1>LATEST
`SUGGESTION`

Check [this comment](#) on using `h1` as top-level heading only.

2019-08-03 12:39 UTC, bolah2009 commented on index.html
> +                    <h1>LATEST
`SUGGESTION`

Check [this comment](#) on using `h1` as top-level heading only.

2019-08-03 12:42 UTC, Anna-Myzukina commented on index.html
> +    <link rel="stylesheet" href="../The-Next-Web/assets/style.css">
Thank`s!

2019-08-03 12:42 UTC, Anna-Myzukina commented on index.html
> +                    <img src="../The-Next-Web/assets/img/Netflix-mobile.jpg" alt="">
Ok!

2019-08-03 12:42 UTC, Anna-Myzukina commented on index.html
> +                    <h1>LATEST
Thank you!

2019-08-05 12:18 UTC, Anna-Myzukina commented on index.html
> +                    <h1>
Of course 1 html document - 1 <h1></h1> ! Omg it`s a really horrible error(( 
Thank`s!

2019-08-05 20:41 UTC, samgaco commented
### Hi @Anna-Myzukina and @maya88en :hand: 

_**Everything looks correct now and you have addressed the corresponding things pointed out by the previous reviewers. Anyways I'd to remark this two points, which are optional but recommended.**_

> ### Optional but strongly recommended
> * Note [this comment](#discussion_r310349641) on file path. Currently, it is preventing the [clone](https://raw.githack.com/maya88en/The-Next-Web/developer/index.html) on raw.githack.com from rendering all asset files.
> * Check out [these errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2Fmaya88en%2FThe-Next-Web%2Fdeveloper%2Findex.html) too.

### Your project is approved. :muscle: You can merge to the master branch and submit the project completion form. Regards!

2019-08-05 23:06 UTC, Oghenebrume50 commented
![11](https://user-images.githubusercontent.com/37092867/62500294-b2fb9b80-b7dd-11e9-98cd-321afad15dba.png)
Hi Team, great work so far but your assets are not linked properly,  currently that is how your webpage looks like, please link them properly. Pay attention to the relative path.

2019-08-06 10:17 UTC, Anna-Myzukina commented on index.html
> +    <link rel="stylesheet" href="../The-Next-Web/assets/style.css">
Thank`s it was useful information & I added githack to make Project demo...

2019-08-06 10:25 UTC, merged